### ISSUE TITLE
📣  Elementor Hello Theme v2.4 Beta 3 Release 📣

### ISSUE THREAD

**Issue by shilo-ey** [elementor/hello-theme#150]
===========

# [Beta 3 UPDATED - PLEASE READ BELOW!](https://github.com/elementor/hello-theme/issues/150#issuecomment-865050268)

===========

Hi Elementor Beta testers 👋,

We introduced our Hello theme to provide web-creators with a conflict-free, and fast website creation process, coupled with Elementor of course. 

As part of our mission to empower web creators and help all Elementor users create professional websites, we are adding a new header and footer functionality to Hello Theme that will allow our free users to create fully functional websites.

Up until today, web creators who use the free version of Elementor could not design and customize a header or edit a footer. **Those days are over.**

Now, users who use Elementor in combination with Hello theme now can do just that. We’ve added additional design possibilities and control when using the Elementor Hello theme. Elementor users will be able to add a customized header and footer to their site faster than ever!

The addition of a header/functionality to Hello Theme will in no way impact Elementor Pro users or hurt the performance of the theme!
 
We invite you to test out the new Header & Footer design capabilities in Hello theme and share your thoughts about this new addition. Think we can make it better or have a suggestion for a different solution? We are open to feedback! Join the discussion and help us create the best possible header/footer experience for our free users.

 
Below are the main topics we will cover in this issue: 

1. Set your Header & Footer layouts
2. Appearance modification options
3. Effect on Hello Theme’s performance
4. How will this impact new vs. existing sites?
5. How does this work with Elementor Pro’s Theme Builder?

#### Before you test, please make sure you are using Elementor v3.1.4, to access the Header and Footer design capabilities (it won’t be available without it).

# Introducing Hello Header & Footer: Design Headers & Footers For Your Sites
![Hello](https://user-images.githubusercontent.com/45009641/111666239-31267d80-881c-11eb-91db-e9ef87baf2b3.png)

Up until now, web creators using the free version of Elementor were unable to create and customize their header and footer using the Hello theme and the free version of Elementor. Instead, they had to find other external solutions or deal with custom code. 

The introduction of free header and footer customization will allow everyone using Elementor Site Settings to create a basic header and footer design for their site. 

To enjoy this new functionality you will need to have downloaded Elementor 3.1.4 and have the Hello Theme 2.4.0 Beta installed and activated. These go hand-in-hand. Without using the Hello Theme you will not be able to create your header and footer. Let’s see what you can do!

### Header & Footer Layouts 

To choose a layout, navigate into your site settings. There, You’ll be able to choose from three basic layouts for your header and footer. 

In the header, you can choose between a Default, Inverted, and Centered layout. 
Each layout contains the site logo, a menu, and tagline which you can decide to show or hide.

**Header layouts:**
![ headers](https://user-images.githubusercontent.com/45009641/111666447-66cb6680-881c-11eb-8a9f-4500e71340d1.png)

In the footer, you’ll have the option to choose from the same layouts as the header. Your footer will also contain the site logo, menu, and copyright which you can choose to show or hide. 

**Footer layouts:**
![footer](https://user-images.githubusercontent.com/45009641/111666466-69c65700-881c-11eb-80f6-8909d4e4a17a.png)

Please keep in mind that If you create a header and footer they will show on all pages, you cannot choose to display them only on specific pages, unless you change the page layout to Canvas. 

### Appearance modification options

In addition to choosing the layouts, you can make some appearance modifications to your header and footer. You can customize the width, background color, menu, appearance and style of each element.

### Effect on Hello Theme’s performance

One of the biggest advantages of Hello Theme is that it’s very lightweight and we put a lot of effort into making sure it remains as such. 
We achieved this by writing the new functionalities to the Elementor plugin - thus minimizing any impact on the theme.
Unless you choose to display the header and footer, the theme will not be affected in any way. 

### How will this impact new vs. existing sites?

All new sites will include the new header and footer functionalities. However, this new addition will not impact your existing sites until you opt-in via the Site Settings. 
 

### How this works with Elementor Pro’s Theme Builder

Elementor pro users are welcome to use the new functionality but **Elementor Pro’s Theme builder already has the same capabilities and much, much more**. We recommend that pro users keep using Theme Builder.
Header and footer sections built using Theme Builder will override Hello Theme in case of a conflict, just like any theme-based header and footer.

#### Here’s how it works:

1. Download the ZIP file of Hello Elementor theme v2.4.0 from the link [you can find here](https://go.elementor.com/hello-theme-beta-2-4/) or in the section below.
2. In WordPress go to Appearance > Themes > Add New > Upload Theme, select the theme file and activate it after you successfully installed it. Make sure you are using Elementor v3.1.4 or above
3. Go to any page and edit it with Elementor
4. Click on the Panel hamburger menu, and access the Site Settings
5. Under the Theme Style section, you will see two new items: Header and Footer
6. Choose either one and start customizing your layout, design, and structure
7. Make sure nothing changed in an existing website
8. Play around with the settings and make sure everything works as expected both on frontend, and in the Editor, in various web-browsers and breakpoints.

### Additional notes:

- Make sure you define the site’s logo, title, and tagline and create at least one menu to enjoy the full functionality of this feature.
- If you are installing on an existing site that already uses the Hello Elementor theme, the header and footer will initially be toggled off - to avoid changing your site’s current look upon upgrading the theme. Don’t worry, you can toggle the new functionality on via Site Settings → Header / Footer

---------------

## How to Install the Beta Version

1. Download Elementor Hello theme 2.4.0 [from the following link](https://go.elementor.com/hello-theme-beta-2-4/)
2. Go to “Appearance” > “Themes”
3. Click “Add New” and “Upload Theme”
4. Choose the Zip file you downloaded in step 1 and click “Install Now”
5. If you already have a previous version of the theme, click “Replace current with uploaded”
6. Activate the theme and try it out

# Notes
For bugs and remarks, please reply with a comment on this issue here on GitHub.
Please keep this related to the Current beta Only! any other issue or feature request, feel free to open a new issue.
Designated time for release: _June 29, 2021 (Estimated)_

**Many thanks for your support and help!**

Cheers,
Elementor Team

**Comment by MichaelDarko** [comment]
So I've tested this and it's totally confusing for Elementor Pro users. I understand this functionality is useful for Elementor without Elementor Pro. But it makes no sense to add this if Elementor Pro is installed.

By default, it adds Header and Footer tab in the site settings, which is very confusing. If I didn't read your explanation here, I would have absolutely no idea why is it there and what it does.

We use the Hello theme because we don't want a theme functionality. The Hello theme should be invisible. Now the theme is adding absolutely obsolete functionality that we have to opt out of, if we want to get rid of it.

If you want to add this feature for Elementor free users, that's fine, but please don't include this for Pro users.

Does this seem like a good idea for user experience? You don't see it as confusing and unnecessary?

The most precious thing the Hello theme could provide is being lightweight and featureless. That's the only thing a Pro user wants from it. Now you're ruining it.

And now the theme starts adding second way to build header/footers by default. The theme should never change the Elementor Pro experience, it should be invisible.

**Comment by gilesholder** [comment]
I agree with the above. I'm also guessing most hello theme users are probably using pro anyway.

**Comment by fabianenzensperger** [comment]
Sorry Shilo, but this function is completely superfluous and does not belong in the Hello theme for me. This is exactly what I think about themes on themeforest and co. always bothered. Just that you are too limited in what you do. Anyone can select a template and click on the logo or click away. But that completely contradicts the Website Builder approach of the Elementor itself (as a plugin) and of course especially in the Pro version.

I want the Hello Theme to do absolutely nothing, except to say to Wordpress "yes, a theme is installed here" and a child theme into which you can add code if necessary.

I just don't understand how you can invest so much time in useless things. $ 49 a year for the Pro version is affordable for absolutely everyone to have this (and many more) function.

Sometimes I really wonder if you're listening to the community and especially your payers. You are wasting so much potential. Sorry, I know that was tough, but maybe there is no other way.

I mean, the Free Beta is so long in coming and then I just have to read some crap about 2.4 Hello Theme. Uff. This "new" approach now really corresponds to everything that makes Elementor ...

**Comment by fabianenzensperger** [comment]
> I agree with the above. I'm also guessing most hello theme users are probably using pro anyway.


Yup. I am also convinced that's the only reasonable way.

If so, it might have been cool to make the theme even lighter out of the box or just add a "Wordpress Widget" area, but in principle it wouldn't have needed anything new.

The theme is great because it can't do anything. And it should stay that way.

**Comment by mcrowell** [comment]
Can you add a feature that will disable these settings if Pro is installed? I find it very confusing as a Pro user to have these header and footer settings in the site settings panel.

**Comment by Jonathlee** [comment]
I have to agree with @MichaelDarko @fabianenzensperger  as the hello theme shall remain as blank, minimal default styling, normalize / reboot.css some style to make the overall Pro Theme work pretty well (sufficiently).

Hello Theme shall remain as blank, with very basic stuff including single-elementor.php to edit Elementor's stuff like header and footer as suggested by @MichaelDarko 

For the header and footer, isn't that covered in https://www.layerswp.com/ sufficient for free users? I thought that was the main reason for Elementor to take over Layers WP theme.

Hello theme shall only include;
- Normalize / Reboot.css
- Bare minimal css, js for user's manual input or hack (e.g. .current-page-ancestor which is not fixed by elementor menu)
- WP Cleaner functions e.g. remove generator, wlwmanifest.xml, emoji, 
- single-elementor_library.php

For Hello Theme, I think the developer side could simply make a poll so we the user could provide you the answer of what users truly need. Ultimately Hello Theme is meant to be as bare minimal and highly optimized.

**Comment by Stimson** [comment]
Writing to agree with the theme of previous comments. Loading up hello with duplicative features defeats its purpose as a lightweight Elementor-friendly theme. I want to use Hello because I can trust it won't become a bloated mess or conflict with My sites using Elementor (pro). This seems like a solution in search of a problem.

**Comment by paauserrat** [comment]
I absolutelly agree with everyone here. I was using hello theme because it was featureless, lighter and faster than other themes. If this theme starts to add funcionality, I will considere choosing another theme. Please, keep adding functionalities to elementor and elementor pro and don't focus on adding features to the theme.

**Comment by rodolphebertozzo** [comment]
Hello to all,
I don't agree with your statement, this feature can be interesting insofar as many people don't want to waste too much time in the design of the header and footer preferring something simple and be satisfied with the only customization features provided in the site settings. We can think of people who do not use Elementor Pro but want to use the Hello theme.

After testing, why push these settings so far? Also, can you add the em unit?
The rest seems to work on my side.
![162817230_852221528690660_6169866545173538694_n](https://user-images.githubusercontent.com/56270626/111826764-6220b400-88e9-11eb-9350-9e72e0b89be3.jpg)

**Comment by fabianenzensperger** [comment]
> Hello to all,
> I don't agree with your statement, this feature can be interesting insofar as many people don't want to waste too much time in the design of the header and footer preferring something simple and be satisfied with the only customization features provided in the site settings. We can think of people who do not use Elementor Pro but want to use the Hello theme.
> 
> After testing, why push these settings so far? Also, can you add the em unit?
> The rest seems to work on my side.
> ![162817230_852221528690660_6169866545173538694_n](https://user-images.githubusercontent.com/56270626/111826764-6220b400-88e9-11eb-9350-9e72e0b89be3.jpg)


No, sorry, it's a complete step backwards and makes absolutely no sense.

If, contrary to expectations, it is of course introduced anyway, it should be completely hidden for pro users, as it is only confusing.

Then this "advertisement" below, which you can create a header / footer with the Theme Builder. Then you don't even get to the new Theme Builder but to the Wordpress backend. Just maximally confusing.

And how should new users even know that this function are in the site settings (which you can only access if you edit a page with Elementor)? It's very hidden.

Especially as a Newbie, which is not a pro user, I imagine that as horror. But well, someone must have thought something here. Maybe.

PS: "waste too much time in design …", sorry but then they are wrong in web**design**.

**Comment by euene** [comment]
Everything that I would've said has already been mentioned by other users here.
- Don't add features to the Hello Elementor theme - it shouldn't have any features
- Why actually include the code in the Elementor plug-in, but enable it only when Hello Elementor theme is used?
- These menus shouldn't exist when Elementor Pro is used, or at the very least they should be buried somewhere under a setting/toggle to turn them on, and be turned off by default with Elementor Pro

**Comment by maurocarreraok** [comment]
> So I've tested this and it's totally confusing for Elementor Pro users. I understand this functionality is useful for Elementor without Elementor Pro. But it makes no sense to add this through a theme and have this if Elementor Pro is installed.
> 
> And if you want to give the free users an ability to design basic headers/footers, why do it through a theme? People won't understand why this feature is there with one theme and not another.
> 
> By default, it adds Header and Footer tab in the site settings, which is very confusing for Pro users. If I didn't read your explanation here, I would have absolutely no idea why is it there, what it does and that it only comes with the Hello theme.
> 
> People won't even understand this feature comes from the theme, because that's not how Elementor works. If you want to add a feature, add it in Elementor, not through a theme.
> 
> We use the Hello theme because we don't want a theme functionality. The Hello theme should be invisible. Now the theme is adding absolutely obsolete functionality (for pro users) that we have to opt out of, if we want to get rid of it.
> 
> Does this seem like a good idea for the Pro user experience? You don't see it as confusing and unnecessary? Why are you suddenly adding features through a theme and not in Elementor itself?
> 
> (I understant that the code was added to Elementor and not the theme, but why is it then related only to the Hello theme?)
> 
> The most precious thing the Hello theme could provide is being lightweight and featureless. That's the only thing a Pro user wants from it.
> 
> **The Hello theme should never add features (Let alone useless and confusing ones!) to the Elementor Pro experience, it should be invisible. We use it because we don't want to think about any theme related settings.**
> 
> Four conceptual mistakes in my opinion:
> 
> * Hello theme should be kept featureless.
> * Features should be added in Elementor, not through a theme.
> * If you want to add a feature, add it to Elementor for everyone, not only for Hello theme users.
> * Features for free users should not cause confusion to pro users.

I've never been 100% agreed with someone. Please, do not take the wrong path...

I know we are not the owners of the product but.... This was something Elementor asked their community? Or something you decided to add just because looks or feel "nice to have"?... 

**I really don't want to have a Hello Theme with features at all... Hello Theme is EXCELLENT for what it is right now... Keep it that way please!**

**Comment by drawcard** [comment]
I can see some pros:
- Quickly scaffold a layout for an initial test build (particularly on a tight schedule)
- Can be completely ignored / overridden by Theme Builder
- Gives Free users a leg up with layout, using common design patterns
- Saves some Pro users from having to build that common design pattern over and over from scratch

But I can see some big cons with this too:
- Adds opinionated features to the theme
- Weakens the Pro offering (why should I upgrade to Theme Builder if the most common design patterns are covered here?)

The idea has good intentions, but to me the cons outweigh the pros. It seems like the value in Pro is diminishing to me when features like this come out to compete against it. I also agree that this theme should be focused on minimalism - the [hello child theme](https://github.com/elementor/hello-theme-child) exists to let users extend it any way they need.

**Comment by drawcard** [comment]
Are there also any plans to address any of the bugs reported in the last 12 months?

**Comment by 100461069** [comment]
elementor het product doet rare dingen de laatste 1 jaar. Prijzen veranderen en geld innen. De blog pagina plaatst bijna nooit tutorials voor het maken van innovaties met elementor, maar blijft blog posts plaatsen met 0 reacties die niets met elementor te maken hebben. Heel vreemd.

**Comment by 100461069** [comment]
elementor the product has been doing some strange things for the last 1 year. Changing prices and ringing up money. The blog page almost never posts tutorials on making innovations with elementor, but keeps posting blog posts with 0 comments that have nothing to do with elementor. Very strange.

**Comment by parasshah195** [comment]
+1 to the above comments. Seems like redundancy and added confusion for Pro customers. Like others mentioned above, I too only install Hello because it's essentially a "blank" theme and allows me to set everything from Elementor Pro for full customization capabilities. If I needed a theme that adds extra functionalities, I'd rather install Astra or some other Elementor-compatible theme.

Adding it in Hello doesn't quite make sense for the purpose it's being widely used (at least I think so..).

**Comment by drawcard** [comment]
Saw this in my inbox today on the beta testing mailing list:
> No code will be loaded when the Pro version of Elementor is detected. All code is optimized for speed.

This is good to hear, but as a Pro user I still feel a little uncomfortable about excessive chunks of code sitting around in all my deployed themes. This feature might not hurt performance, but it potentially hurts security as the surface of attack has increased in my theme. "Less is more" should be the principle of a good scaffold theme.

**Comment by Elsteck** [comment]
The Hello theme is not meant to be used by EFree users, it is barebones for a reason. Even with the option to create headers and footers it is not a good choice for EFree users to work with the Hello theme because it misses all styled themeparts. Or is that next on the agenda?

**Comment by augustoms** [comment]
Indeed. For me, it makes no sense to provide this kind of functionality in the theme.
Hope that this discussion makes the devs change their mind.

> So I've tested this and it's totally confusing for Elementor Pro users. I understand this functionality is useful for Elementor without Elementor Pro. But it makes no sense to add this through a theme and have this if Elementor Pro is installed.
> 
> By default, it adds Header and Footer tab in the site settings, which is very confusing for Pro users. If I didn't read your explanation here, I would have absolutely no idea why is it there, what it does and that it only comes with the Hello theme.
> 
> People won't even understand this feature comes from the theme, because that's not how Elementor works. If you want to add a feature, add it in Elementor, not through a theme.
> 
> Does this seem like a good idea for the Pro user experience? You don't see it as confusing and unnecessary? Why are you suddenly adding features through a theme and not in Elementor itself?
> 
> (I understant that the code was added to Elementor and not the theme, but why is it then related only to the Hello theme?)
> 
> The most precious thing the Hello theme could provide is being lightweight and featureless. That's the only thing a Pro user wants from it.
> 
> **The Hello theme should never add features (Let alone useless and confusing ones!) to the Elementor Pro experience, it should be invisible. We use it because we don't want to think about any theme related settings.**
> 
> Four conceptual mistakes in my opinion:
> 
> * Hello theme should be kept featureless.
> * Features should be added in Elementor, not through a theme.
> * If you want to add a feature, add it to Elementor for everyone, not only for Hello theme users.
> * Features for free users should not cause confusion to pro users.

**Comment by acornavi** [comment]
Elementor development team lives in a parallel universe where more bloat makes a good product. This so-called update is "senseless". Take care of what really matters, like bloat, add functionality that people really need, like form conditions, etc. People are moving more and more away from Elementor because of this kind of move, without real perspective and creativity.

**Comment by Vossha** [comment]
I'm curious and confused to be honest about how this decision was made? As a Hello user but also as a business owner/product maker.

Elementor is trying to combine 2 contradicting audiences into one product when adding a feature like this. Free users and Pro users. That doesn't work. 

**You are changing and playing with the products promise,** which is dangerous for any business. The promise was: Hello is not for features. The Hello theme was created as a barebone solution for Elementor Pro users. You can't just change a products promise/usage case/problem. 

And I can't help but think that Elementor knows. Because this decision is just weird and illogical. So please, if you want to stop offering a barebone theme, please be honest and communicate with us so Hello users can search for other solutions. From human to human, I write this as a happy Elementor user, we're all in for the best and we want to help each other. But don't just change a products promise out of the blue. 

### Other possible solution for adding a feature like this:
Add the feature to the free Elementor plugin.

or

Create a completely different theme for free users, next to the Hello theme.

All other themes > New Lightweight Elementor foundation theme for free users > Barebone Hello theme for pro user.

This way Elementor offers something for every user while extending their toolkit. Plus, you're not changing core promises of products that already exist (free or paid).

**Comment by black-eye** [comment]
> I'm curious and confused to be honest about how this decision was made?

Yes, this kind of reminds me of an old video, from their blog and social media:


https://user-images.githubusercontent.com/5634870/112698594-46d61b80-8e8a-11eb-9b67-5ab55041cf6e.mp4


https://www.youtube.com/watch?v=QuL0XHKp0Lg&t=125s


What was meant as a joke back then in 2020, has become the sad reality in these days: development driven by random choices... :-(

Yes, I know, I'm not being 100% fair here, a lot of good stuff was done as well. But the clear vision has been lacking - or at least can't be seen from the outside of the developers' universe - users' universe.

I feel so sad as I'm writing this - it's so frustrating to see such a good product moving in such weird directions ... :-(

**Comment by awakekat** [comment]
I am an Elementor Expert who helps people learn Elementor. I have been teaching older adults for 25 years. In the last week alone I have gotten 3 clients that are using Astra Free with Elementor Pro. I have had to spend several hours trying to find reasons why someone would use a theme that does the exact same thing as Elementor Pro. I am not here to bash Astra, I am here to say that if you choose to put a bare bones header footer builder inside of Hello... MAKE IT VERY CLEARLY OBVIOUS HOW TO TURN IT OFF when they do decide to move to Elementor Pro. And make a very detailed video explaining it.

**Comment by MikeLikesThat** [comment]
Short Summary:
How I currently build headers and footers is by using templates to add conditions to enable or disable them as needed for landing pages. So my question is are you able to just allow the free version of Elementor to be able to create Header and Footer templates, disabling condition options?

v2.4 Beta Review:
Setup is straight forward and I feel most, if not all, of the past clients that I rebuilt their sites for, would be able to figure this out. Most of them understood to edit the design they would navigate to Appearance - Customize. This is good as you have a Header & Footer tab with the "start here" button.

Making basic edits works but the "Color" and "Toggle Color" under Menu don't work properly. I found it easier to just go back one to Theme Style - Typography - Link and then setting the normal and hover state there.

In the footer, there is a bug when editing the Menu typography it actually is changing the Copyright typography.

Final Thoughts:
To me, for Elementor this makes sense on trying to make a header/footer editor. There is an obvious need as there are 1+ Million Active Installations of "Elementor – Header, Footer & Blocks Template" by Brainstorm Force and 300,000+ Active Installations of "Elements kit Elementor addons (Header & Footer Builder, Mega Menu Builder, Layout Library)" by Wpmet. 

I don't believe the Hello Theme approach is ideal as it is clearly known as a "barebones" theme. So my question is are you able to just allow the free version of Elementor to be able to create Header and Footer templates, disabling condition options, in addition to the Page, Section, and Landing Page templates? This would leave the Hello Theme users happy, have free customers use the Templates tab to see your other offerings like Popups to possibly upsell them, and keep the drag and drop widgets concept fluid throughout the Elementor experience.

**Comment by petranca** [comment]
I chose the theme because it didn't contain anything useless. Now it's changing, so there's no reason to update. Or I make my own theme, call it "Bye Elementor". 😂

**Comment by d19dotca** [comment]
I'm surprised after all these comments (almost all of the same mindset and same advice to the Elementor team), that we haven't received any updates or responses yet from the E team. I hope we will hear something this week perhaps. I realize today is a stat holiday in certain countries/states/provinces so unlikely to see any response today, but hoping we'll see an update / responses to our feedback this week sometime.

**Comment by shilo-ey** [comment]
Hello everyone!

**Thank you for taking the time to share your insights and feedback.**

According to your recommendations, we will modify this option and it will be added as an experiment in the Experiments screen (Elementor > Settings > Experiments). this way, existing sites won’t get affected and you will need to opt-in to this feature in every existing website.

As I mentioned above this is not meant to affect our Theme Builder users in any way will not impact the performance of Hello Theme.

We are open to your suggestions, please feel free to continue to share your thoughts and ideas with us.

**Comment by fabianenzensperger** [comment]
> Hello everyone!
> 
> **Thank you for taking the time to share your insights and feedback.**
> 
> According to your recommendations, we will modify this option and it will be added as an experiment in the Experiments screen (Elementor > Settings > Experiments). this way, existing sites won’t get affected and you will need to opt-in to this feature in every existing website.
> 
> As I mentioned above this is not meant to affect our Theme Builder users in any way will not impact the performance of Hello Theme.
> 
> We are open to your suggestions, please feel free to continue to share your thoughts and ideas with us.

Nice that you are think about it at least a little. But I would actually leave it out completely. 98% of those 25 comments here don't think that's a good thing.

If you really want to implement that, ask the 100k Elementor Facebook group how the idea is received there. Maybe even with a vote!

**Comment by drawcard** [comment]
Thanks @shilo-ey I think that's a great solution.

**Comment by blue928** [comment]
I agree. This is completely the wrong direction. It's almost like the devs are adding things as a means of job security. A lot has been happening over the past year at Elementor that has really alienated pro users, and this is a great example of such changes that just don't make any sense.

If you want the Free members to have functionality, add it to Elementor itself. Or, fork this project and have a "hello pro" and "hello free." Don't just add bloat for the sake of adding bloat. I use the blank canvas for 95% of my projects. You just made my code base unnecessarily heavy for features I will never use, and neither will any pro member.

If you really want to impress us with a great theme, go the opposite direction. Make it smaller, make it faster, make it more streamlined. At this point you've complicated it enough that I now have a lot of options I consider when choosing a theme whereas before it was a no-brainer to choose this one.

I have to agree with the comments and insinuations a lot of other people have stated. Did you guys have a change in management or something? It's like you are throwing darts at a wall of random things saying, "what will we work on today?"

If you had been listening to your community over the years, you would know that this is exactly the wrong direction. How this made it to beta, much less out of a boardroom meeting baffles me. It's just another example of confusing decisions you guys have made over the last year to two years, ultimately causing us to lose confidence in the direction you are headed with the project overall.

**Comment by fabianenzensperger** [comment]
> I agree. This is completely the wrong direction. It's almost like the devs are adding things as a means of job security. A lot has been happening over the past year at Elementor that has really alienated pro users, and this is a great example of such changes that just don't make any sense.
> 
> If you want the Free members to have functionality, add it to Elementor itself. Or, fork this project and have a "hello pro" and "hello free." Don't just add bloat for the sake of adding bloat. I use the blank canvas for 95% of my projects. You just made my code base unnecessarily heavy for features I will never use, and neither will any pro member.
> 
> If you really want to impress us with a great theme, go the opposite direction. Make it smaller, make it faster, make it more streamlined. At this point you've complicated it enough that I now have a lot of options I consider when choosing a theme whereas before it was a no-brainer to choose this one.
> 
> I have to agree with the comments and insinuations a lot of other people have stated. Did you guys have a change in management or something? It's like you are throwing darts at a wall of random things saying, "what will we work on today?"
> 
> If you had been listening to your community over the years, you would know that this is exactly the wrong direction. How this made it to beta, much less out of a boardroom meeting baffles me. It's just another example of confusing decisions you guys have made over the last year to two years, ultimately causing us to lose confidence in the direction you are headed with the project overall.


I 1000000% agree.

**Comment by Elsteck** [comment]
@shilo-ey 
Wow, you not only violate the purpose of the Hello theme, but also that of the recently introduced Experiments, when launched this was: “ Elementor Experiments is a way for Elementor users, if they choose, to test and help shape new features before they are released.”

And for what? Do you really think a barebones theme serves the Elementor Free user, that has a multitude of great free themes to choose from that not only let him create a custom header and footer, but also makes his site, his blog and pages look good, something the current Hello theme will definitely do not!

Please serve the Pro users a plain barebones theme, they are the ones who invested too.

**Comment by fxaviers** [comment]
First of all, I'm not saying this in order to create hate.
I love Elementor, 4 years ago E-Pro helps me to create websites in a very uncomplicated way, which I didn't have before, now I can better serve my small clients in the interior of Brazil (yes, I am not native in English).

For a year and a half my discontent with the direction that the company Elementor has been taking only increases, much of it is due to attitudes like this issue or the lack of a greater connection with the E-Pro community.
We are customers, we are not in a position to demand much, but in any issue the only return we have is to close it or simply silence.
With the exception of the (still small) improvement in the DOM output, all the rest released in the latest versions were just cosmetic items, which do not really represent an innovative functionality, or that solved problems or requests already widely discussed here on GitHub.

I'm fully aware that it is impossible to share strategic information, but what I always asked for was a more tangible return: "We are not going to do this, look for add-ons", or "We intend to implement this in the distant future", or "is in the plans for the next year" would be great.
They would be much more transparent, and we would have a return to better manage our own companies, if we would expect native functionality, if we would look for a complement or even look for another builder.

I hate comparisons, but Elementor has reached a stage where several features are present in competitors and we don't know what to expect. As a businessman, I know it is a delicate point, but leaving customers in the dark I consider an even worse position.

Anyway, forgive me for my outburst, but for all I have seen, this is the feeling of other users.

**Comment by drawcard** [comment]
Without wanting to go off-topic here - as much as we've all been criticising Elementor over this, at least a solution has come about which doesn't affect Elementor Hello theme and that's what matters. That's why I keep paying for Elementor Pro - despite the fact they have to please millions of users, they'll still listen to a dozen or so users in a beta thread and adapt accordingly. That's a rarity in the software world these days so hats off to them.

**Comment by roman75323** [comment]
I read the comments above, and I think that it is not entirely correct, on the contrary, they added an excellent feature (header, footer) ... what I need to assemble the main page in HTML and use the proposed header and footer option. I like. Please continue the development and whoever likes the previous version, let it use it, it won't hurt anyone.

**Comment by fabianenzensperger** [comment]
Hello? 👀

**Comment by iamgigabyte** [comment]
Less is more.

Please turn your focus to the speed and efficiency of Elementor and optimizing code output rather than adding more features.  I cannot see the Elementor community asking for more bulk in the Hello theme as this would be exactly counter to its purpose - an absolutely *minimal* theme for Elementor Pro users.  It was never intended to compensate Elementor (free) users for things that were exclusive to Elementor Pro.

Besides, Elementor (free) users would certainly choose a different theme that already offers a header and footer builder like the free version of Astra.  They would not a choose a theme that purposely omits all but the bare minimum features.

**Comment by 79ho3ein** [comment]
Friends, what's the problem that all users are unhappy with this update?
Can you explain?

**Comment by fabianenzensperger** [comment]
> Friends, what's the problem that all users are unhappy with this update?
> Can you explain?


Because the Hello Theme should not get any functions. That's what Elementor Pro is for.

If you want a header, you can look for a different theme. So easy.

**Comment by 79ho3ein** [comment]
Did elementor opt out of this update due to user opposition?

**Comment by d19dotca** [comment]
> Did elementor opt out of this update due to user opposition?

It's unclear at the moment. Last we heard in this thread they still wanted to do it but would leave it as an option instead of being enabled by default. See their comment here: https://github.com/elementor/hello-theme/issues/150#issuecomment-815990378

**Comment by fabianenzensperger** [comment]
> Did elementor opt out of this update due to user opposition?



> Did elementor opt out of this update due to user opposition?
> Because its release date has passed.


It's still in beta, so it's not officially released yet.

My last stand is that the developers will put it in the "experiments" section. But I think they haven't found a final solution yet. In another thread, write @shilo-ey , they'll get in touch when they have news for us.

**Comment by 79ho3ein** [comment]
I hope elementor does not make things difficult for us. As a user, I prefer elementor to work on optimizing its theme. Do not add unnecessary features.

**Comment by 79ho3ein** [comment]
@shilo-ey 
Excuse me, can you tell us about the latest elementor decision about this update?
This update has worried many users. Please reply.

thanks

**Comment by fabianenzensperger** [comment]
> I hope elementor does not make things difficult for us. As a user, I prefer elementor to work on optimizing its theme. Do not add unnecessary features.


That's exactly the point.

**Comment by 79ho3ein** [comment]
The most important thing that elementor needs to improve is optimizing its code.I can not understand the decision to add a header and footer.
I hope it will be reconsidered. Elementor definitely does not want to lose its users.

**Comment by 79ho3ein** [comment]
I am writing a request for this update on github for elementor. Please support.
Thanks

**Comment by d19dotca** [comment]
> I am writing a request for this update on github for elementor. Please support.
> Thanks

The appropriate place for a discussion on the Hello Theme is in this very thread. I'd recommend closing the ticket you opened in the main Elementor repository because the Hello Theme is a different product and is thus handled inside the Hello Theme repository instead - where we are discussing this here already.

**Comment by 79ho3ein** [comment]
thank you my friend. I did not know about this. Thanks for letting us know.

**Comment by nreljed** [comment]
I propose your attention for this  **game changer** function 🤞🙏🙏
[#156 ](https://github.com/elementor/hello-theme/issues/156)

**Comment by roman75323** [comment]
Good day, if you like, I will help your team in many ways, and the elementary in general.  I am not a developer, but at the same time, I know how to help your team in development (if you listen, if not, then write).  this is my last attempt to reach out to your team

Отправлено с iPhone

**Comment by avivu** [comment]
Hello All,

We just released a [new beta version (beta 2).](https://github.com/elementor/hello-theme/files/6166057/hello-theme.zip)


First, I would like to thank all of you for your comments and suggestions. 
We took the time to rethink this feature based on the feedback you shared and made some changes accordingly. 

Let’s start with the why:
Your concerns about the performance of Hello theme are valid, and we want to emphasize that this is not an ongoing process or change that is coming to this theme. This is STILL a plain theme. 

Hello theme should handle all site aspects only to the ones who want to use Elementor (free version) to create a fully functional site, therefore we modified the new Header and Footer feature to be less intrusive by marking it as an Experiment  in Elementor’s Experiments screen (Elementor > Settings > Experiments). 

This way, existing sites won’t get affected, and you will need to opt-in to this feature if needed. Don’t want to use it? nothing will change and you will be able to keep working on a plain vanilla theme without extra functionality that is being loaded.

We believe that many of our users will benefit from this new functionality - create a complete website using Elementor. Note that this change will not affect you, our Pro users, because just like any other theme that registers a header - it won’t be active if you use the Theme Builder features.

We invite you to test out the new version and share your thoughts about the latest changes:

- Tweak: Added Hello theme Header and footer as an Elementor Experiment
- Fix: Layout glitch in header mobile menu
- Fix: Layout is not consistent with sections in Header and Footer
- Fix: Missing max-width to the toggle holder
- Fix: Missing content width control in header when layout set to center
- Fix: Footer on a tablet device is not full width when set to full width
- Fix: The header menu disappears on tablet device when breakpoint set to Mobile(<768px)
- Fix: Footer copyright text not changed in the editor in live editing
- Fix: Header & Footer appear in Customize when the Experiment is inactive
- FIx: Horizontal and Dropdown menu appears at the same time when switching between them in edit mode


Please keep all comments related to the current beta only! For any other issue or feature request, feel free to open a new issue.

Thank you! Looking forward to your feedback.

**Comment by fabianenzensperger** [comment]
> Hello All,
> 
> We just released a [new beta version (beta 2).](https://github.com/elementor/hello-theme/files/6166057/hello-theme.zip)
> 
> First, I would like to thank all of you for your comments and suggestions.
> We took the time to rethink this feature based on the feedback you shared and made some changes accordingly.
> 
> Let’s start with the why:
> Your concerns about the performance of Hello theme are valid, and we want to emphasize that this is not an ongoing process or change that is coming to this theme. This is STILL a plain theme.
> 
> Hello theme should handle all site aspects only to the ones who want to use Elementor (free version) to create a fully functional site, therefore we modified the new Header and Footer feature to be less intrusive by marking it as an Experiment in Elementor’s Experiments screen (Elementor > Settings > Experiments).
> 
> This way, existing sites won’t get affected, and you will need to opt-in to this feature if needed. Don’t want to use it? nothing will change and you will be able to keep working on a plain vanilla theme without extra functionality that is being loaded.
> 
> We believe that many of our users will benefit from this new functionality - create a complete website using Elementor. Note that this change will not affect you, our Pro users, because just like any other theme that registers a header - it won’t be active if you use the Theme Builder features.
> 
> We invite you to test out the new version and share your thoughts about the latest changes:
> 
> * Tweak: Added Hello theme Header and footer as an Elementor Experiment
> * Fix: Layout glitch in header mobile menu
> * Fix: Layout is not consistent with sections in Header and Footer
> * Fix: Missing max-width to the toggle holder
> * Fix: Missing content width control in header when layout set to center
> * Fix: Footer on a tablet device is not full width when set to full width
> * Fix: The header menu disappears on tablet device when breakpoint set to Mobile(<768px)
> * Fix: Footer copyright text not changed in the editor in live editing
> * Fix: Header & Footer appear in Customize when the Experiment is inactive
> * FIx: Horizontal and Dropdown menu appears at the same time when switching between them in edit mode
> 
> Please keep all comments related to the current beta only! For any other issue or feature request, feel free to open a new issue.
> 
> Thank you! Looking forward to your feedback.


I think it's a good compromise. For the future, it would be nice to find another solution to enable or disable certain functions of Elementor (widgets) or the theme. Maybe like this

The list of experiments is slowly getting long and confusing.

**Comment by 79ho3ein** [comment]
hi @avivu 
When will the official version be released?
Has the new version worked on optimizing the code?

**Comment by d19dotca** [comment]
> I think it's a good compromise. For the future, it would be nice to find another solution to enable or disable certain functions of Elementor (widgets) or the theme. Maybe like this
> 
> The list of experiments is slowly getting long and confusing.

Agreed! The experiment list is long now and the whole premise of experiments is that they're temporary (they'll eventually move into a fully-baked feature or be removed), so once it is promoted to a fully-baked feature then what is the situation there for those who wanted it off, for example? Hopefully that will be thought of too.

Thank you for listening to our feedback though and rethinking your approach. We appreciate it! 😃

**Comment by fxaviers** [comment]
> This is STILL a plain theme.

Maybe it's a confusion of words on my part (since I'm not native), but if I'm right, this "STILL" makes me slightly worried.

At the moment it's a plain vanilla theme, but what we're all looking for with Hello Theme is that it's **ALWAYS** a vanilla theme. Just as little as possible, lighter, simpler, minimal.

As others have said above, experiments aren't forever and sometimes it will be built in natively, everything we don't want when using Hello Theme.

Need to add more features? Make a new theme, and each one uses what is best for their reality.

**Comment by avivu** [comment]
@fabianenzensperger - Thank you! We will address the Experiments screen and try to find a good solution to all sides.

@79ho3ein - Offical release should be in two weeks. Stay tuned for more updates later on :)

@d19dotca - As mentioned above, we will try to find a solution for the Experiments screen.
Regarding the Hello Theme - don't worry; we will not change the new behavior. Thanks!

@fxaviers - We also want and will keep Hello Theme as light as possible, and it's not going to be an ongoing process of adding features to the theme. We will consider your other suggestions. 

Thank you all! :)

**Comment by 79ho3ein** [comment]
> @79ho3ein - Offical release should be in two weeks. Stay tuned for more updates later on :)

Thank you for your efforts. Good luck.

**Comment by 79ho3ein** [comment]
hi @avivu 
I use hello theme to design my projects. But there is a problem with most plugins, especially crocoblock plugins. All clickable elements (with link)
Once clicked, they have an outline. I will show you this problem below :
Before clicking : https://prnt.sc/15ubgez That is not a problem
After clicking : https://prnt.sc/15ubjv8 After clicking, a black border appears.

I did not see this problem in other formats.I contacted crocoblock support, they said there was a problem with the theme. And must be solved by the theme developers.
This problem with the code: outline: none; Is solved, but The number of these cases is so large that it is very time consuming to code for each of them.
Please fix this problem in future update if possible.

thanks you.

**Comment by avivu** [comment]
Hi @79ho3ein 
Thank you for the input; we will take a look and examine this issue, but first, please open a new issue that is not related to the current beta thread, so it won't get lost once the beta issue is closed.

Thank you!

**Comment by avivu** [comment]
Hey all,
We just released a new beta version; please update your [version to v2.4.0 Beta 2](https://github.com/elementor/hello-theme/files/6166057/hello-theme.zip).

Please note that this beta version is our release candidate that supposed to be released by 29/06/2021.

This beta release includes:

- Tweak: Updated Elementor admin notices UI
- Fix: footer-has-copyright class remained when Copyright toggled off
- Fix: Header & Footer styling not loading on non-Elementor pages
- Fix: Mobile menu not triggering on non-Elementor pages


Please keep all comments related to the current beta only! For any other issue or feature request, feel free to open a new issue.

Thanks again to everyone!

**Comment by fabianenzensperger** [comment]
@avivu Unfortunately, I still don't understand the meaning behind this new "feature" from the Hello Theme. It is absolutely incomprehensible to me why Elementor spends time and money developing such useless things.

There is not a single person I have read here or elsewhere that this feature is needed. Rather the opposite, it will be very much wondered what has ridden you.

Unfortunately, at a meeting with the chief developers @shilo-ey  and @Dor_s , I forgot to ask what must have happened to make you think this function could be useful. I just do not understand.

Now we have a new update in a few days that I won't even begin to install. It then buzzes around in the experiments, everyone will wonder what this is about and hardly anyone will use it. And if a free user user should, he will feel ripped off because you are very limited.

And doesn't Elementor want to be exactly the opposite? Unlimited?

Why not perfect a function (theme builder and the nav menu widgets including more sticky options) instead of bringing up a mess that just takes extra work and annoyances?

Just wanted to share my thoughts on it again. Me and there I speak I think for everyone, don't want a Hello Theme that has (unnecessary) functions. For my part, fix the requests that are listed as an issue, but please let go of that.

And I'm really sorry that I'm so hard. But this really annoys me. I've been looking so long for a theme that can't do anything and that performs well. It may still be afterwards, but it won't feel like that anymore.

If I get an answer to these concerns here, please answer me in detail and don't avoid any sentences. I want to understand. And please don't say it might be useful. That's not true.

**Comment by matheuscardosodesigner** [comment]
I still don't understand how everyone can't see a clear use for this. I confess, I am a heavyuser of Elementor Free, and I always look for external extensions when I want to create a header for my clients. I create basic sites, which are not worth using Elementor Pro in my country, $49 = R$242.98, which becomes totally unfeasible in some cases where I charge R$500.00 per site.

But back to functionality. It's simple, most themes already come with this function, what's the problem with hello that it's the best theme there is to have one?

+1 for the feature.

**Comment by fxaviers** [comment]
> It's simple, most themes already come with this function

For a very simple reason, Hello Theme was created to be as simple as possible. If you want to change header and footer, look for another theme.
Changing this principle midway is counterproductive. 

I completely understand your point, our currency is very undervalued, but that is no reason to implement the function in the theme.

**Comment by Elsteck** [comment]
> what's the problem with hello that it's the best theme there is to have one

Hello is not the best theme to work with Elementor Free. Introducing basic, very basic header and footer feature does not make it the perfect fit that it is with Elementor Pro. All the controls are missing, the single and archive look like crap. When you want a great theme for Elementor Free then best go with a high featured one like Blocksy.

The best theme for Elementor Pro was Hello, it was never meant to be used with Free and adding this header/footer is so fundamentally wrong. The same goes for the Experiments solution. That was meant for new features that when fully ironed out would move out of experiments into the core. All this is incomprohensible.

**Comment by d19dotca** [comment]
The Elementor team find this video (from WPTuts) worth a watch as it does a decent job at explaining the concerns listed out earlier: https://youtu.be/UJk6s2B-bWs

**Comment by awakekat** [comment]
Please start another theme and name it something else and leave Hello for the developers to do what they want with nothing to slow them down. PLEASE!!

**Comment by alexcumbers** [comment]
Can you please check / advise the Beta 3 link ASAP? It still points to Beta 1 !
https://github.com/elementor/hello-theme/files/6166057/hello-theme.zip
Beta 1 is not compatible with Elementor 3.2.x
thanks

**Comment by alexcumbers** [comment]
And the original Hello Beta 1 is pinned in GitHub, can we get this one pinned please

**Comment by shilo-ey** [comment]
> @avivu Unfortunately, I still don't understand the meaning behind this new "feature" from the Hello Theme. It is absolutely incomprehensible to me why Elementor spends time and money developing such useless things.
> 
> There is not a single person I have read here or elsewhere that this feature is needed. Rather the opposite, it will be very much wondered what has ridden you.
> 
> Unfortunately, at a meeting with the chief developers @shilo-ey and @Dor_s , I forgot to ask what must have happened to make you think this function could be useful. I just do not understand.
> 
> Now we have a new update in a few days that I won't even begin to install. It then buzzes around in the experiments, everyone will wonder what this is about and hardly anyone will use it. And if a free user user should, he will feel ripped off because you are very limited.
> 
> And doesn't Elementor want to be exactly the opposite? Unlimited?
> 
> Why not perfect a function (theme builder and the nav menu widgets including more sticky options) instead of bringing up a mess that just takes extra work and annoyances?
> 
> Just wanted to share my thoughts on it again. Me and there I speak I think for everyone, don't want a Hello Theme that has (unnecessary) functions. For my part, fix the requests that are listed as an issue, but please let go of that.
> 
> And I'm really sorry that I'm so hard. But this really annoys me. I've been looking so long for a theme that can't do anything and that performs well. It may still be afterwards, but it won't feel like that anymore.
> 
> If I get an answer to these concerns here, please answer me in detail and don't avoid any sentences. I want to understand. And please don't say it might be useful. That's not true.

Hey @fabianenzensperger ,

Thank you for your sincere feedback.

We DO want to allow unlimited capabilities to everyone, even if they are not our Pro users,
In addition, we want to provide our users with free template Kits, which now can be found in beta 3.3.0. 

This will allow users who want to - to create a full website without paying anything and still keep the simplicity of Elementor and Hello Theme.



> Can you please check / advise the Beta 3 link ASAP? It still points to Beta 1 !
> [elementor/hello-theme/files/6166057/hello-theme.zip](https://github.com/elementor/hello-theme/files/6166057/hello-theme.zip)
> Beta 1 is not compatible with Elementor 3.2.x
> thanks

Thanks, link updated >> [Download now](https://go.elementor.com/hello-theme-beta-2-4/)


Thanks

**Comment by gilesholder** [comment]
It's quite clear that on here and on Hello Git no developer is wanting this functionality!

As you guys insist on including it why not add it as a standalone plugin to extend Hello & Elementor Free?

You could then just add a simple message system to the hello theme such as:

- If hello is installed and only Elementor free is installed display a message promoting the standalone plugin.
- If hello is installed and Elementor pro is installed display no message.

This way you can easily do updates to the header & builder, track usage, dedicated support etc for this. 

I am sure anyone using free will not mind an extra plugin as if you are using pro you need pro as an extra anyway.

Most serious developers anyway modify Hello to their needs and this would reduce the updates to the theme to actually only be core updates.

Not rocket science, but would keep all of your developers happy!

**Comment by d19dotca** [comment]
> This will allow users who want to - to create a full website without paying anything and still keep the simplicity of Elementor and Hello Theme.

Doesn't this kind of devalue Elementor Pro though if features that were generally Pro-only are being released (even if limited) to everybody using the free version?

**Comment by 79ho3ein** [comment]
My friends, I did not understand what you meant. That is, the hello template becomes a professional and non-free version?
Can you explain?
thank you

**Comment by avivu** [comment]
Hello All,
After a long period of beta and optimizations, we just released Hello Theme v2.4.0.

We want to thank all of you for your comments and suggestions. Our main focus in this version is to allow every user who wants to, to create a fully functioning website using the free version of Elementor, and still keep the simplicity of Elementor and Hello Theme.

As you know, we are marking this feature as an Experiment - this way, existing sites won’t get affected, and you will need to manually opt-in to this feature.

For any other issue or feature request, feel free to open a new issue.
Thank you!
